name: CI/CD Pipeline - BankApp - WAR + Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target branch for testing (manual)'
        required: false
        default: 'testbeforedeploy'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BASE_IMAGE: aryan9511/aryan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Set image name by branch
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ -n "${{ github.head_ref }}" ]]; then
            BRANCH="${{ github.head_ref }}"
          fi

          if [[ "$BRANCH" == "main" ]]; then
            echo "IMAGE_NAME=${BASE_IMAGE}:tag3" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "testbeforedeploy" ]]; then
            echo "IMAGE_NAME=${BASE_IMAGE}:tagtest" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=${BASE_IMAGE}:latest" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME

  deploy-to-ec2:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/testbeforedeploy'
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: Set image name by branch
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ -n "${{ github.head_ref }}" ]]; then
            BRANCH="${{ github.head_ref }}"
          fi

          if [[ "$BRANCH" == "main" ]]; then
            echo "IMAGE_NAME=aryan9511/aryan:tag3" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "testbeforedeploy" ]]; then
            echo "IMAGE_NAME=aryan9511/aryan:tagtest" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=aryan9511/aryan:latest" >> $GITHUB_ENV
          fi

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull $IMAGE_NAME
            docker stop baas-container || true
            docker rm baas-container || true
            docker run -d --name baas-container -p 8080:8080 $IMAGE_NAME
          EOF
